function finalPoint=JudgeStudentsPoint()
load '6formation_results.mat'


k = 0.5;

%% statistics position error, include x, y and z
% absPositionError = sum(abs(get(thtraj1, 'XData')-get(ehtraj1, 'XData'))+abs(get(thtraj1, 'YData')-get(ehtraj1, 'YData'))+abs(get(thtraj1, 'ZData')-get(ehtraj1, 'ZData')) ...
%     +abs(get(thtraj2, 'XData')-get(ehtraj2, 'XData'))+abs(get(thtraj2, 'YData')-get(ehtraj2, 'YData'))+abs(get(thtraj2, 'ZData')-get(ehtraj2, 'ZData')) ...
%     +abs(get(thtraj3, 'XData')-get(ehtraj3, 'XData'))+abs(get(thtraj3, 'YData')-get(ehtraj3, 'YData'))+abs(get(thtraj3, 'ZData')-get(ehtraj3, 'ZData')) ...
%     +abs(get(thtraj4, 'XData')-get(ehtraj4, 'XData'))+abs(get(thtraj4, 'YData')-get(ehtraj4, 'YData'))+abs(get(thtraj4, 'ZData')-get(ehtraj4, 'ZData')) ...
%     +abs(get(thtraj5, 'XData')-get(ehtraj5, 'XData'))+abs(get(thtraj5, 'YData')-get(ehtraj5, 'YData'))+abs(get(thtraj5, 'ZData')-get(ehtraj5, 'ZData')) ...
%     +abs(get(thtraj6, 'XData')-get(ehtraj6, 'XData'))+abs(get(thtraj6, 'YData')-get(ehtraj6, 'YData'))+abs(get(thtraj6, 'ZData')-get(ehtraj6, 'ZData'))); % 1.2014e+03
% 
absPositionError = sum(abs(thtraj1.X-ehtraj1.X)+abs(thtraj1.Y-ehtraj1.Y)+abs(thtraj1.Z-ehtraj1.Z) ...
    +abs(thtraj2.X-ehtraj2.X)+abs(thtraj2.Y-ehtraj2.Y)+abs(thtraj2.Z-ehtraj2.Z) ...
    +abs(thtraj3.X-ehtraj3.X)+abs(thtraj3.Y-ehtraj3.Y)+abs(thtraj3.Z-ehtraj3.Z) ...
    +abs(thtraj4.X-ehtraj4.X)+abs(thtraj4.Y-ehtraj4.Y)+abs(thtraj4.Z-ehtraj4.Z) ...
    +abs(thtraj5.X-ehtraj5.X)+abs(thtraj5.Y-ehtraj5.Y)+abs(thtraj5.Z-ehtraj5.Z) ...
    +abs(thtraj6.X-ehtraj6.X)+abs(thtraj6.Y-ehtraj6.Y)+abs(thtraj6.Z-ehtraj6.Z));
    
    

%% statistics speed error, include x and y 
absSpeedError = sum(abs(ehvx1.Y-thvx1.Y)+abs(ehvy1.Y-thvy1.Y) ...
    +abs(ehvx2.Y-thvx2.Y)+abs(ehvy2.Y-thvy2.Y) ...
    +abs(ehvx3.Y-thvx3.Y)+abs(ehvy3.Y-thvy3.Y) ...
    +abs(ehvx4.Y-thvx4.Y)+abs(ehvy4.Y-thvy4.Y) ...
    +abs(ehvx5.Y-thvx5.Y)+abs(ehvy5.Y-thvy5.Y) ...
    +abs(ehvx6.Y-thvx6.Y)+abs(ehvy6.Y-thvy6.Y));

finalPoint = k*(absPositionError + absSpeedError) / 100 + (1-k) * time;
disp(['your performance score is: ' , num2str(finalPoint)]);    %27.9835
end